### ISSUE TITLE
Problem installing SMTP Gateway Plugin for RabbitMQ [UBUNTU 14.04]

### ISSUE THREAD

**Issue by mauricio-cardenas-tierconnect-com** [gotthardp/rabbitmq-email#1]
I tried to make the installation from source and in the last process I have this issue with the "make" inside rabbitmq-email on ubuntu:

Ouput.

../do-package.mk:168: ../gen_smtp/package.mk: No such file or directory
[elided] generate deps
[elided] fix test deps
sed -e 's|../coverage/build/deps.mk|$(DEPS_FILE)|' ../coverage/build/deps.mk > ../coverage/build/deps.mk.tmp && mv ../coverage/build/deps.mk.tmp ../coverage/build/deps.mk
[elided] generate deps
[elided] fix test deps
sed -e 's|../gen_smtp/build/deps.mk|$(DEPS_FILE)|' ../gen_smtp/build/deps.mk > ../gen_smtp/build/deps.mk.tmp && mv ../gen_smtp/build/deps.mk.tmp ../gen_smtp/build/deps.mk
make: **\* No rule to make target `../gen_smtp/package.mk'.  Stop.

What else can I do to fix to get the plugin?

**Comment by gotthardp** [comment]
We discussed this also at https://groups.google.com/forum/#!topic/rabbitmq-users/K8Rm8zKT300
Is the problem solved? May I close the issue?

**Comment by mauricio-cardenas-tierconnect-com** [comment]
Of course! thank you so much...

**Comment by mauricio-cardenas-tierconnect-com** [comment]
Yes please, thank you so much

Regards

Mauricio
