### ISSUE TITLE
Handling attachments

### ISSUE THREAD

**Issue by Miljar** [gotthardp/rabbitmq-email#18]
I've been able to succesfully build, activate & use this plugin to process incoming SMTP messages with a consumer. Now I want to handle attachments as well. I've tried several of the configurations mentioned for `email_filter`, but none seems to be doing anything with an attachment. Is this functionality available, or am I not configuring the plugin correctly?

**Comment by michaelklishin** [comment]
What do you expect to happen with the attachments? Messaging protocols typically do not have a concept of files. How should attachments be handled?

Also, what _exactly_ are you trying to do?

**Comment by Miljar** [comment]
I'm currently working on a web application where customers can create a "project". All communication about their project should be available in a UI. I'm now doing this by using e-mails in the form of `<project-uuid>@<domain>` and have this plugin put those mails on a queue for processing. When an attachment is added to an e-mail, that attachment should be made available in their "project library".

Maybe the easiest way would be for this plugin to provide the raw mail data (headers & body) in the AMQP message, so I can parse the data myself & extract the attachments from that information.

**Comment by gotthardp** [comment]
By setting `{email_filter, false}` you will get the entire MIME message with all body parts. Is that what you want?

**Comment by Miljar** [comment]
I have tried several configurations of `email_filter`. When I set it to `false`, this is what a mail with attachment looks like when I get it in the rabbitmq web interface:

```
Exchange    email-in
Routing Key dossier==51e5a2d3-3d14-4219-865a-eeeb1f08f122@dossiers.hypodroom.dev
Redelivered ○
Properties  
timestamp:  1454401023
message_id: 1804f23a69ad024a27f84d4749b1b83c
delivery_mode:  2
headers:    
charset:    UTF-8
content_type:   text/plain
Payload
134 bytes
Encoding: string
Hey,

Does this mail arrive with an attachment?



-- 
    Tom Van Herreweghe <mailto:tom@king-foo.be>
PHP Developer
http://king-foo.be
```

It looks like the Payload contains a text version of the mail.

What I want is a way to get the attachments from the mail (a PDF and the image from the signature). Maybe the easiest way for you to provide this, is some kind of option to provide the raw e-mail data in the AMQP message. This way, if you really want, you could do anything you want with the mail.

Do you want me to send my mail with attachment to the proposed test queue at "rabbitmq[at]swimgate.eu"?

**Comment by gotthardp** [comment]
I guess you either have an old version of the plug-in (please check you have at least v0.0.2), or you have a configuration error (please check you have `{server_auth, false}` in your `rabbitmq_email` config section). I can review your rabbitmq.config if you include it here.
Just to be sure, please send the e-mail to the proposed test address.

**Comment by Miljar** [comment]
I followed the instructions with EICONV enabled and ended up with `rabbitmq_email-0.1.0.ez`, `gen_smtp-0.9.0.ez` and `eiconv-1.1.ez`.

Originally, I had `{server_auth, rabbitmq}` and I switched it to `{server_auth, false}` in my config. After restarting the rabbitmq-server, I saw no change. This is my entire config:

```
[
  {rabbit, [
        {tcp_listeners, [{"0.0.0.0", 5672}]},
        {rabbitmq_email, [
          {server_config, [
              [{port, 2525}, {protocol, tcp}, {domain, "dossiers.hypodroom.dev"}, {address,{0,0,0,0}}]
          ]},
          {server_auth, false},
          {server_starttls, false},
{email_filter, false},
          {email_domains,
              [{<<"dossiers.hypodroom.dev">>, {<<"/">>, <<"email-in">>}}
              ]},
          {email_queues,
              [{
                  {<<"/">>, <<"email-out">>}, <<"dossiers.hypodroom.dev">>}
              ]},
          {client_sender, "noreply@example.com"}
      ]}
  ]}
].
```

Is my config OK?

I have sent a test e-mail to the test address too.

**Comment by Miljar** [comment]
I was testing this functionality by configuring my e-mail client to send the mail via a postfix server on a test machine. I have also tried sending an e-mail directly to the rabbitmq-email plugin via command line: `sendemail -f tom@king-foo.be -t dossier==123@dossiers.hypodroom.dev -m "This is the message" -u "This is the subject" -a /vagrant/codeception-bak.yml -s 0.0.0.0:2525 -o username=admin -o password=admin` but still no luck.

**Comment by gotthardp** [comment]
The rabbitmq_email section is misplaced: it should be in the top-level list, not under the `rabbit` section. The config should be like this:

``` erlang
[
  {rabbit, [
        {tcp_listeners, [{"0.0.0.0", 5672}]}
  ]},
  {rabbitmq_email, [
     {server_config, [
         [{port, 2525}, {protocol, tcp}, {domain, "dossiers.hypodroom.dev"}, {address,{0,0,0,0}}]
     ]},
     {server_auth, false},
     {server_starttls, false},
     {email_filter, false},
     {email_domains,
         [{<<"dossiers.hypodroom.dev">>, {<<"/">>, <<"email-in">>}}
         ]},
     {email_queues,
         [{
             {<<"/">>, <<"email-out">>}, <<"dossiers.hypodroom.dev">>}
         ]},
     {client_sender, "noreply@example.com"}
  ]}
].
```

**Comment by Miljar** [comment]
Ok, that indeed fixed everything.
I can't believe I made a stupid mistake like that. So all the time it was kind off working, it was pure luck :)

Thanks!
