### ISSUE TITLE
Get full email headers in rabbitmq

### ISSUE THREAD

**Issue by samjadmooppan** [gotthardp/rabbitmq-email#23]
I was able to pull the messages from the rabbitmq queue using nodejs. However it shows a very limited set of email headers. The operation is that the email is sent to email@github.com from  me@myself.com and email@github.com is then forwarded to a third  email  github@app.mydomain.com.  The email user github@app.mydomain.com is configured in Postfix + rabbitmq-email .

In this scenario, I am able to obtain only the from and to headers(From : me@myself.com and To :email@github.com ), while I also need the complete headers to decide what to do with the message received. In short , I badly need header line with the final email its reaching (github@app.mydomain.com).

**Comment by gotthardp** [comment]
The current implementation offers two possibilities:
- add the headers you need to the `email_headers` list
- set `{email_filter, false}` and parse the entire message yourself

**Comment by samjadmooppan** [comment]
thanks :) . Worked like a charm
