### ISSUE TITLE
Problem building plugin 

### ISSUE THREAD

**Issue by sledwich** [gotthardp/rabbitmq-email#25]
Hi, I am looking to use the plugin have installed the current version of rabbitmq from Fedora REPO (v3.6.5)

When I issue the build its failing with the following error:

init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
error: rabbitmq-components.mk must be updated!
rabbitmq-components.mk:324: recipe for target 'check-rabbitmq-components.mk' failed
make: *** [check-rabbitmq-components.mk] Error 1

I have checked the crash dump and could not find anything to help. Any help much appreciated. thanks

**Comment by gotthardp** [comment]
try `make rabbitmq-components-mk`

see https://www.rabbitmq.com/plugin-development.html

**Comment by sledwich** [comment]
Thanks for your reply, It gave me the same error:

>make rabbitmq-components-mk
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
 GEN    rabbitmq-components-mk

I am reading the crash dump but its not very clear as to where the problem is. But it seems to have the same problem in do_boot.

Thanks

**Comment by gotthardp** [comment]
The code was just ported to the latest RabbitMQ, so this should be fixed now.
