### ISSUE TITLE
Using it on windows

### ISSUE THREAD

**Issue by fayeeg** [gotthardp/rabbitmq-email#28]
Hi,

Could anyone assist how to utilize rabbitmq-email on windows ( esp. on Windows 10 64-bit & Server 2012 )?

I see makefile can be used only linux/unix environments. Whether cygwin can be used to build the sources?

Regards,
Fayeeg

**Comment by michaelklishin** [comment]
msys2 works well for RabbitMQ and all of the built-in plugins. I see no reason for it to not work here. Or just download an existing build.

**Comment by fayeeg** [comment]
Thanks for your response. Could you please give me the link to download the existing build?

**Comment by michaelklishin** [comment]
I'm not aware of anything newer than https://github.com/gotthardp/rabbitmq-email/releases. We offered @gotthardp some help with bringing this plugin up-to-date with the 3.6.x build system and received no response. The offer is still on the table.

**Comment by fayeeg** [comment]
Sorry for being ignorant. I am a windows guy, thought build release means final compiled output i. e plugins files that somewhere I can download from. 

I did try downloading the latest build...did make..got the following error




$ git clone https://github.com/gotthardp/rabbitmq-email.git
Cloning into 'rabbitmq-email'...
remote: Counting objects: 338, done.
remote: Total 338 (delta 0), reused 0 (delta 0), pack-reused 338
Receiving objects: 100% (338/338), 142.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (211/211), done.

MSYS /d/teamprojects
$ cd rabbitmq-email

MSYS /d/teamprojects/rabbitmq-email
$ make dist
 DEP    rabbit_common
error: rabbitmq-components.mk must be updated!
make: *** [rabbitmq-components.mk:324: check-rabbitmq-components.mk] Error 1

**Comment by michaelklishin** [comment]
@fayeeg this plugin needs updating for the RabbitMQ 3.6.x build system.

**Comment by fayeeg** [comment]
I followed the steps explained in https://github.com/gotthardp/rabbitmq-email/issues/8
```
$ git clone https://github.com/rabbitmq/rabbitmq-public-umbrella.git
$ cd rabbitmq-public-umbrella
$ git checkout rabbitmq_v3_5_6
$ make co
$ ./foreachrepo git checkout rabbitmq_v3_5_6
$ git clone https://github.com/gotthardp/rabbitmq-gen-smtp.git
$ git clone https://github.com/gotthardp/rabbitmq-eiconv.git
$ git clone https://github.com/gotthardp/rabbitmq-email.git
$ cd rabbitmq-email
$ git checkout v0.0.2
$ make
-----------------------------------------------------------------------


I changed...
$ git checkout rabbitmq_v3_5_6
to
$ git checkout rabbitmq_v3_6_12

AND 

$ ./foreachrepo git checkout rabbitmq_v3_5_6
to 
$ ./foreachrepo git checkout rabbitmq_v3_6_12


In the last step, I am getting the below errors and make does not produce 'dist' f


Fayeeg@Jupiter MSYS /d/teamprojects/rabbitmq-public-umbrella/rabbitmq-email
$ make
(no error logger present) error: <0.10.0>
(no error logger present) error: <0.8.0>
(no error logger present) error: <0.9.0>
(no error logger present) error: <0.12.0>
(no error logger present) error: <0.22.0>
(no error logger present) error: <0.16.0>
(no error logger present) error: <0.20.0>
(no error logger present) error: <0.15.0>
(no error logger present) error: <0.26.0>
(no error logger present) error: <0.30.0>
(no error logger present) error: <0.13.0>
(no error logger present) error: <0.11.0>
(no error logger present) error: <0.17.0>
(no error logger present) error: <0.14.0>
(no error logger present) error: <0.21.0>
(no error logger present) error: <0.18.0>
(no error logger present) error: <0.27.0>
(no error logger present) error: <0.25.0>
(no error logger present) error: <0.23.0>
(no error logger present) error: <0.19.0>
(no error logger present) error: <0.24.0>
(no error logger present) error: <0.29.0>
(no error logger present) error: <0.28.0>
```



help is appreciated.

**Comment by michaelklishin** [comment]
@fayeeg please see the comment above. This plugin **is known to be out of date** with the current RabbitMQ build system. We will update it soon.

**Comment by fayeeg** [comment]
I wish I had known this before.  I spent hours.  When likely we can have the update?

**Comment by michaelklishin** [comment]
@fayeeg 0.2.0 is already available from GitHub releases and Bintray. See the README ;)

**Comment by fayeeg** [comment]
Thanks a bunch. I already installed the latest plugins and working fantastic.
