### ISSUE TITLE
Support  Multipart/Related Content-Type

### ISSUE THREAD

**Issue by xtang** [gotthardp/rabbitmq-email#4]
When processing mail whose content-type is `Multipart/Related`, the plugin will throw function_clause error.

**Comment by gotthardp** [comment]
Which revision of the rabbitmq-email are you using? Could you share the error log here?

**Comment by gotthardp** [comment]
I enhanced and fixed the body filtering functions. Would you be able to test the master branch?

**Comment by gotthardp** [comment]
Fixed by commit 4efc2b12a49bf729266107410700e313ee711ddf.
