### ISSUE TITLE
Config - New Format Style

### ISSUE THREAD

**Issue by softronsts** [gotthardp/rabbitmq-email#40]
Could anyone please provide the config in new config format style for below rabbitmq_email old format?

[
  {rabbitmq_email, [
    %% gen_smtp server parameters
    %% see https://github.com/Vagabond/gen_smtp#server-example
    {server_config, [
        [{port, 25}, {protocol, tcp}, {domain, "xxx.com"}, {address,{127,0,0,1}}]
    ]},
    %% how clients are authenticated; either 'false' or 'rabbitmq' (default)
    {server_auth, rabbitmq},
    %% whether STARTTLS shall be offered; either 'true' or 'false' (default)
    {server_starttls, true},
	{email_headers, ["subject", "from", "charset"]},
    {email_filter, false},
    {email_domains,
        [{<<"xxx.com">>, {<<"/">>, <<"email-in">>}}
    ]},

    %% outbound email queues: [{{vhost, queue}, email-domain}, ...]
    {email_queues,
        [{{<<"/">>, <<"email-out">>}, <<"xxxx.com">>}
    ]},
    %% sender indicated in the From header
    {email_from, <<"xxxxx">>},
    %% sender indicated in the SMTP from
    {client_sender, "xxxxxxx"},
    %% gen_smtp client parameters
    %% see https://github.com/Vagabond/gen_smtp#client-example
    {client_config, [
        {relay, "mail.xxx.com"},{username, "xxxxxx"}, {password, "xxxxx"},{port, 26}
    ]}
  ]}
].

Please note when I try to use the old style format in advanced.config, rabbitmq server unable to start.

**Comment by lukebakken** [comment]
> Please note when I try to use the old style format in advanced.config, rabbitmq server unable to start.

The new style is not supported, and you must use `advanced.config`. You must actually tell us what is going wrong in your environment. This means providing the following information:

* RabbitMQ version
* Erlang version
* Operating system and version
* Version of this plugin
* _Attach_ all configuration files to your response. Do *not* paste them!
* _Attach_ an archive of your RabbitMQ logs. Do *not* paste them!

**Comment by softronsts** [comment]
Thanks for the tips. I managed to track the log files and found smtp tcp port issue. I have changed to different port and all in order now. Thanks again,
