### ISSUE TITLE
rabbitmq-server failed to start after enabling the rabbitmq_email plugin

### ISSUE THREAD

**Issue by Rohan-Rajak** [gotthardp/rabbitmq-email#42]
Hello there,

I have installed the rabbitmq_email plugin v0.4.0 in RabbitMQ 3.8.9 with erlang version 21.3.8.7. But after enabling the plugin when I restarted the rabbitmq-server service, the service failed to start. I checked the logs and it is related to the plugin. We have tried with the plugin version 0.3.0 but the issue is the same.

I have also tried with RabbitMQ version 3.7.x but the result is the same.

To make sure that the issue is with the plugin, I disabled the plugin and tried to restart the service again. The service started without any issue.

It will be really beneficial if you may help with this issue.

**Comment by lukebakken** [comment]
Thanks for using RabbitMQ. Without more information we can't assist:

* Operating system used
* How did you download, install and enable this plugin? How was it disabled?
* Full log files showing failure, as well as any other logs

If the above information is provided I will re-open this issue. Please **attach** files to your response. Do not paste large amounts of text.

**Comment by Rohan-Rajak** [comment]
Hello there,

Please find the following information as required-

- Operating System: CentOS Linux release 7.7.1908 (Core)

- I downloaded the .ez files of the rabbitmq_email plugin and gen_smtp plugin from https://github.com/gotthardp/rabbitmq-email/releases -> copied the .ez files into the plugin directory of rabbitmq -> then ran the command "rabbitmq-plugins enable rabbitmq_email" to enable the plugin

To disable the plugin I ran "rabbitmq-plugins disable rabbitmq_email"

- Log files are attached
[rabbit@rabbit-email.zip](https://github.com/gotthardp/rabbitmq-email/files/5686791/rabbit%40rabbit-email.zip)

**Comment by Rohan-Rajak** [comment]
Hello there,

Please reopen the issue

**Comment by lukebakken** [comment]
These errors are probably related to the changes here: https://github.com/rabbitmq/rabbitmq-server/issues/2180

They may be resolved by this PR: https://github.com/rabbitmq/rabbitmq-server/pull/2656

**Comment by Rohan-Rajak** [comment]
Hello,

I checked this PR rabbitmq/rabbitmq-server#2656 but didn't find any solution there. As per the PR, the solution is still under work. Please correct me if I am wrong.

**Comment by lukebakken** [comment]
@Rohan-Rajak RabbitMQ `3.8.10` will ship with a fix for this. Please watch the [`rabbitmq-users`](https://groups.google.com/g/rabbitmq-users) mailing list for announcements about Release Candidates and test with an RC in your environment.
