### ISSUE TITLE
Unable to send HTML email

### ISSUE THREAD

**Issue by softronsts** [gotthardp/rabbitmq-email#50]
[errorlog-detailed.txt](https://github.com/gotthardp/rabbitmq-email/files/8214829/errorlog-detailed.txt)

My application is attempting to send HTML email. This exact process worked fine in the old version. I have attached the error log here. Looking forward to your guidance.

Ubuntu 20.04
RabbitMQ - 3.9.13
Erlang - 23.2

Plugin built with the latest source.

**Comment by lukebakken** [comment]
See #51, I will be re-tagging version 1.0.1 within the hour.

**Comment by lukebakken** [comment]
Fixed in https://github.com/gotthardp/rabbitmq-email/commit/a345674934f9a40ed8f13987437358a55422a407

Thank you for the log!

**Comment by softronsts** [comment]
Working great ! Thanks for your prompt fix.

**Comment by lukebakken** [comment]
Thank you for confirming the fix.
