### ISSUE TITLE
Unable to send mail 

### ISSUE THREAD

**Issue by a-marcellini** [gotthardp/rabbitmq-email#51]
You are syncing the dev. version of gen_smtp, however in the readme you declare the dependency to the 1.1.1.
What's more I'm not sure if your code acknowledges the mimemail encode modification: from list to map.
[here the code](https://github.com/gen-smtp/gen_smtp/blob/628863f0bfd4439678bf216da5c1f55626ec2a8e/src/mimemail.erl#L80)

I'm not an erlang expert, however, I think that the code doesn't use maps as parameter but it uses lists:

Look at rabbit_email_sender.erl row 22 as an example, 4th parameter:
Message = mimemail:encode({Type, Subtype, lists:foldr(fun set_header/2, [], Headers2), [], Payload}),

I succesfully tested the following fix:
Message = mimemail:encode({Type, Subtype, lists:foldr(fun set_header/2, [], Headers2), #{}, Payload}),

I'm going to create a branch and a pull request.

**Comment by lukebakken** [comment]
Thanks for the offer but I have already fixed this in https://github.com/gotthardp/rabbitmq-email/pull/49 and have tagged version 1.1.1 of this project - https://github.com/gotthardp/rabbitmq-email/releases/tag/v1.0.1

**Comment by lukebakken** [comment]
I misread the `gen_smtp` code, sigh. I'll get this fixed.

**Comment by lukebakken** [comment]
Fixed in https://github.com/gotthardp/rabbitmq-email/commit/a345674934f9a40ed8f13987437358a55422a407
