### ISSUE TITLE
Unable to build anymore

### ISSUE THREAD

**Issue by a-marcellini** [gotthardp/rabbitmq-email#52]
Hi,
hi tried to build the project. It worked until 8/April but  not It doesn't build anymore.
The strange thing is that we haven't changed anything since then.
The error we get is the following:

```
#13 34.48 make[1]: Entering directory '/root/rabbitmq-email/.erlang.mk/rabbitmq-server/deps/rabbit_common'
#13 34.50  DEP    rabbitmq_codegen (master)
#13 34.51 error: no valid pathspec among:  master master master
#13 34.51 make[1]: *** [../../erlang.mk:5102: /root/rabbitmq-email/deps/rabbitmq_codegen] Error 1
#13 34.51 make[1]: Leaving directory '/root/rabbitmq-email/.erlang.mk/rabbitmq-server/deps/rabbit_common'
#13 34.51 make: *** [erlang.mk:8082: /root/rabbitmq-email/.erlang.mk/recursive-deps-list.log] Error 2
```

What we see is that the symbolic links to the modules are not created, but we ignore the reason.

Here you can find our try:
https://github.com/sistemi-iungo/rabbitmq-email/pull/1

Maybe there has been a change on the rabbitmq side?

**Comment by lukebakken** [comment]
> Maybe there has been a change on the rabbitmq side?

Yes, `master` branches have been renamed to `main`, and probably other changes. I'll get to this issue this month.

**Comment by a-marcellini** [comment]
> > Maybe there has been a change on the rabbitmq side?
> 
> Yes, `master` branches have been renamed to `main`, and probably other changes. I'll get to this issue this month.

Thank you very much! 
The impossibility for us to change the message size limit of gen_smtp through a configuration change is giving us several problems. 
So your promptness is very appreciated!
