### ISSUE TITLE
Unable to fetch 'from'

### ISSUE THREAD

**Issue by tepsl** [gotthardp/rabbitmq-email#6]
If incoming email's From header value begins with '=?UTF-8?B?', 'from' header of AMQP message is not included or empty.
The character encodings other than UTF-8 in MIME/Base64 seems to be OK.

**Comment by gotthardp** [comment]
Please make sure you have the eiconv enabled (see README). When eiconv is disabled, the email handler will pass through all '=?UTF-8?B?' characters. They should not disappear though. I did some tests and it seems to work on my end.
Could you please post here a sample From header with '=?UTF-8?B?' that doesn't work for you?

**Comment by tepsl** [comment]
Sorry for late reply.
It is probable that the reason isn't by From header.
I cannot post the e-mail that doesn't work because it includes actual e-mail address.
Empirically, many e-mails from gmail do not work.

**Comment by gotthardp** [comment]
Even mails from gmail work for me. Could you please re-send the mails that don't work for you to my instance of the plugin at rabbitmq[at]swimgate.eu?

**Comment by tepsl** [comment]
I cannot send any mails that didn't work.
The mails I had tested worked before our system was publicly released.
The mails didn't work were from active system and that must be closed.
If I detect problematic pattern, I'll let you know.
