### ISSUE TITLE
security and raw message

### ISSUE THREAD

**Issue by waynebrantley** [gotthardp/rabbitmq-email#7]
1)  Is there a way to secure this SMTP endpoint?

2)  Is there a way to just put the entire message - all contents, attachments into a single message and pass that along instead of any parsing?

**Comment by gotthardp** [comment]
1) You should be able to listen on a SSL port by configuring `{protocol, ssl}` in the _server_config_. The uderlying [gen_smtp](https://github.com/Vagabond/gen_smtp) seem to allow that, but I have never tried that.

2) You want all attachements, or attachements _and_ MIME headers? You should be able to configure the email_filter to give you all attachements. Sending MIME headers would require enhancements in the implementation.

**Comment by waynebrantley** [comment]
Secure the endpoint as in a username/password....not just transport security.

**Comment by gotthardp** [comment]
OK, I see what you mean. I will implement username/password authentication and make the filtering engine optional.

**Comment by gotthardp** [comment]
Done. You can set `{email_filter, false}` to disable filtering and `{server_auth, rabbitmq}` to authenticate clients against the rabbitmq database.

Binaries will be released once the next RabbitMQ server is out.
